const GeoLayout yoshi_yoshi_filled_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_player_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_switch_option_yoshi_head_fill_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt1_jump_yoshi_yoshi_filled_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_player_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_switch_option_yoshi_head_fill_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 61, -5, 0, 90, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_skl_root_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_player_part_from_parent),
					GEO_ASM(0, geo_player_tilt_torso),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, 25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_l1_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_leg_l2_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_l2_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_ankle_l1_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, -25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_r1_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_leg_r2_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_r2_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_ankle_r1_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_spin_skinned_mesh_layer_1),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 10, 0, yoshi_spin_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_l1_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, 23, 0, -90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_arm_l1_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_l2_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 20, 0, 0, yoshi_arm_l2_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_wrist_l1_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 19, 0, 0, yoshi_wrist_l1_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_r1_skinned_mesh_layer_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, -23, 0, 90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_arm_r1_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_r2_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 20, 0, 0, yoshi_arm_r2_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_wrist_r1_skinned_mesh_layer_1),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, 0, 0, 0, 1, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_wrist_r1_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 0, 2, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_yoshi_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_player_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_face_1_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_mouth_skinned_mesh_layer_1),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, -2, 180),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_TRANSPARENT, 2, -11, 0, yoshi_mouth_mesh_layer_1),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, -9, -21, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_tongue_tip_skinned_mesh_layer_1),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 184, 44, 0, 0, -92, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_tongue_tip_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, yoshi_cap_switch_function_opt1_jump_yoshi_yoshi_filled_001),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt2_jump_yoshi_yoshi_filled_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_player_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_switch_option_yoshi_head_fill_mesh_layer_1_mat_override_metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 61, -5, 0, 90, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_skl_root_mesh_layer_1_mat_override_metal_0),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_player_part_from_parent),
					GEO_ASM(0, geo_player_tilt_torso),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, 25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_l1_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_leg_l2_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_l2_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_ankle_l1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, -25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_r1_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_leg_r2_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_r2_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_ankle_r1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_spin_skinned_mesh_layer_1_mat_override_metal_0),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 10, 0, yoshi_spin_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_l1_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, 23, 0, -90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_arm_l1_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_l2_skinned_mesh_layer_1_mat_override_metal_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 0, yoshi_arm_l2_mesh_layer_1_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_wrist_l1_skinned_mesh_layer_1_mat_override_metal_0),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 0, 0, yoshi_wrist_l1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_r1_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, -23, 0, 90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_arm_r1_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_r2_skinned_mesh_layer_1_mat_override_metal_0),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 0, yoshi_arm_r2_mesh_layer_1_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_wrist_r1_skinned_mesh_layer_1_mat_override_metal_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, 0, 0, 0, 1, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_wrist_r1_mesh_layer_1_mat_override_metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 0, 2, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_yoshi_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_player_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_face_1_mesh_layer_1_mat_override_metal_0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_mouth_skinned_mesh_layer_1_mat_override_metal_0),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, -2, 180),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 2, -11, 0, yoshi_mouth_mesh_layer_1_mat_override_metal_0),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, -9, -21, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_tongue_tip_skinned_mesh_layer_1_mat_override_metal_0),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 184, 44, 0, 0, -92, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_tongue_tip_mesh_layer_1_mat_override_metal_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, yoshi_cap_switch_function_opt2_jump_yoshi_yoshi_filled_001),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt3_jump_yoshi_yoshi_filled_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_player_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, 0, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_switch_option_yoshi_head_fill_mesh_layer_1_mat_override_metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_cap_switch_function_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 61, -5, 0, 90, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_skl_root_mesh_layer_1_mat_override_metal_0),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_player_part_from_parent),
					GEO_ASM(0, geo_player_tilt_torso),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, 25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_l1_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_leg_l2_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_l2_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_ankle_l1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, -25, 0, -180, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_r1_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_leg_r2_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_leg_r2_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_ankle_r1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_spin_skinned_mesh_layer_1_mat_override_metal_0),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 10, 0, yoshi_spin_mesh_layer_1_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_l1_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, 23, 0, -90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_arm_l1_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_l2_skinned_mesh_layer_1_mat_override_metal_0),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 20, 0, 0, yoshi_arm_l2_mesh_layer_1_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_wrist_l1_skinned_mesh_layer_1_mat_override_metal_0),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 19, 0, 0, yoshi_wrist_l1_mesh_layer_1_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_r1_skinned_mesh_layer_1_mat_override_metal_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, -23, 0, 90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_arm_r1_mesh_layer_1_mat_override_metal_0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_arm_r2_skinned_mesh_layer_1_mat_override_metal_0),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 20, 0, 0, yoshi_arm_r2_mesh_layer_1_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_wrist_r1_skinned_mesh_layer_1_mat_override_metal_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, 0, 0, 0, 1, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_wrist_r1_mesh_layer_1_mat_override_metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 0, 2, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_player_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_yoshi_face),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_player_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_face_1_mesh_layer_1_mat_override_metal_0),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_mouth_skinned_mesh_layer_1_mat_override_metal_0),
															GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, -2, 180),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_TRANSPARENT, 2, -11, 0, yoshi_mouth_mesh_layer_1_mat_override_metal_0),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, -9, -21, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, yoshi_tongue_tip_skinned_mesh_layer_1_mat_override_metal_0),
																		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 184, 44, 0, 0, -92, 0),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, yoshi_tongue_tip_mesh_layer_1_mat_override_metal_0),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, yoshi_cap_switch_function_opt3_jump_yoshi_yoshi_filled_001),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout yoshi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 179, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 65536),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, geo_switch_player_cap_effect),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 61, -5, 0, 90, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_skl_root_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_move_player_part_from_parent),
									GEO_ASM(0, geo_player_tilt_torso),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, 25, 0, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_l1_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_leg_l2_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_l2_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_ankle_l1_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -3, -8, -25, 0, -180, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_r1_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_leg_r2_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_leg_r2_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -20, 0, 0, 180, 0),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_ankle_r1_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_spin_skinned_mesh_layer_1),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 10, 0, yoshi_spin_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_l1_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, 23, 0, -90, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_arm_l1_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_l2_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 0, yoshi_arm_l2_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_wrist_l1_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 19, 0, 0, yoshi_wrist_l1_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_r1_skinned_mesh_layer_1),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 29, -23, 0, 90, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_arm_r1_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_arm_r2_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 0, yoshi_arm_r2_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_wrist_r1_skinned_mesh_layer_1),
														GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, 0, 0, 0, 1, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_wrist_r1_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 43, 0, 0, 2, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_player_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_yoshi_face),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_player_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_face_1_mesh_layer_1),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_mouth_skinned_mesh_layer_1),
																			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5, 1, 0, 0, -2, 180),
																			GEO_OPEN_NODE(),
																				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																				GEO_OPEN_NODE(),
																					GEO_ANIMATED_PART(LAYER_OPAQUE, 2, -11, 0, yoshi_mouth_mesh_layer_1),
																					GEO_ANIMATED_PART(LAYER_OPAQUE, -9, -21, 0, NULL),
																					GEO_OPEN_NODE(),
																						GEO_DISPLAY_LIST(LAYER_OPAQUE, yoshi_tongue_tip_skinned_mesh_layer_1),
																						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 184, 44, 0, 0, -92, 0),
																						GEO_OPEN_NODE(),
																							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, yoshi_tongue_tip_mesh_layer_1),
																						GEO_CLOSE_NODE(),
																					GEO_CLOSE_NODE(),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, yoshi_yoshi_filled_001),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, yoshi_cap_switch_function_opt1),
					GEO_BRANCH(1, yoshi_cap_switch_function_opt2),
					GEO_BRANCH(1, yoshi_cap_switch_function_opt3),
				GEO_CLOSE_NODE(),
				GEO_ASM(0, geo_mirror_player_backface_culling),
				GEO_ASM(0, geo_mirror_player_set_alpha),
				GEO_ASM(1, geo_mirror_player_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
