const GeoLayout mips_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4_mat_override_mips_orange_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_orange_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4_mat_override_mips_orange_0),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_orange_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4_mat_override_mips_orange_0),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4_mat_override_mips_orange_0),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4_mat_override_mips_orange_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_orange_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4_mat_override_mips_orange_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4_mat_override_mips_orange_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_orange_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4_mat_override_mips_orange_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_orange_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4_mat_override_mips_orange_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_orange_0),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4_mat_override_mips_orange_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_orange_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4_mat_override_mips_orange_0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_orange_0),
												GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4_mat_override_mips_orange_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_orange_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4_mat_override_mips_orange_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_orange_0),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4_mat_override_mips_orange_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_orange_0),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4_mat_override_mips_orange_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4_mat_override_mips_orange_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mips_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4_mat_override_mips_pink_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_pink_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4_mat_override_mips_pink_1),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_pink_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4_mat_override_mips_pink_1),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4_mat_override_mips_pink_1),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4_mat_override_mips_pink_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_pink_1),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4_mat_override_mips_pink_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4_mat_override_mips_pink_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_pink_1),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4_mat_override_mips_pink_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_pink_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4_mat_override_mips_pink_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_pink_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4_mat_override_mips_pink_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_pink_1),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4_mat_override_mips_pink_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_pink_1),
												GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4_mat_override_mips_pink_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_pink_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4_mat_override_mips_pink_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_pink_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4_mat_override_mips_pink_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_pink_1),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4_mat_override_mips_pink_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4_mat_override_mips_pink_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mips_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4_mat_override_mips_green_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_green_2),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4_mat_override_mips_green_2),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_green_2),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4_mat_override_mips_green_2),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4_mat_override_mips_green_2),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4_mat_override_mips_green_2),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_green_2),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4_mat_override_mips_green_2),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4_mat_override_mips_green_2),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_green_2),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4_mat_override_mips_green_2),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_green_2),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4_mat_override_mips_green_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_green_2),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4_mat_override_mips_green_2),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_green_2),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4_mat_override_mips_green_2),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_green_2),
												GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4_mat_override_mips_green_2),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_green_2),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4_mat_override_mips_green_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_green_2),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4_mat_override_mips_green_2),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_green_2),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4_mat_override_mips_green_2),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4_mat_override_mips_green_2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mips_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4_mat_override_mips_white_3),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_white_3),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4_mat_override_mips_white_3),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_white_3),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4_mat_override_mips_white_3),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4_mat_override_mips_white_3),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4_mat_override_mips_white_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_white_3),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4_mat_override_mips_white_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4_mat_override_mips_white_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_white_3),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4_mat_override_mips_white_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_white_3),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4_mat_override_mips_white_3),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_white_3),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4_mat_override_mips_white_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_white_3),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4_mat_override_mips_white_3),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_white_3),
												GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4_mat_override_mips_white_3),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_white_3),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4_mat_override_mips_white_3),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_white_3),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4_mat_override_mips_white_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_white_3),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4_mat_override_mips_white_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4_mat_override_mips_white_3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mips_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 150, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4_mat_override_mips_cyan_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4_mat_override_mips_cyan_4),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4_mat_override_mips_cyan_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4_mat_override_mips_cyan_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4_mat_override_mips_cyan_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4_mat_override_mips_cyan_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4_mat_override_mips_cyan_4),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4),
												GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4_mat_override_mips_cyan_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4_mat_override_mips_cyan_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_cyan_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4_mat_override_mips_cyan_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4_mat_override_mips_cyan_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4_mat_override_mips_cyan_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mips_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(6, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_SHADOW(0, 150, 100),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_FORCE, 16384),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 94, -72, 0, -90, 50),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_skl_root_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_l1_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, -36, 0, 0, -100),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_l1_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_arm_r1_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 85, -66, 36, 0, 0, -100),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_arm_r1_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 69, 0, 0, 0, 0, -35),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_head1_mesh_layer_4),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, -25, 0, 5, 95),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l1_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_l2_skinned_mesh_layer_4),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_l2_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, 119, 25, 0, -5, 95),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r1_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ear_r2_skinned_mesh_layer_4),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 83, 0, 0, 0, 0, -120),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ear_r2_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l1_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, -49, 0, 0, -75),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l1_mesh_layer_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_l2_skinned_mesh_layer_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_l2_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l1_skinned_mesh_layer_4),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_l1_mesh_layer_4),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_l2_skinned_mesh_layer_4),
														GEO_ANIMATED_PART(LAYER_ALPHA, 145, 0, 0, mips_ankle_l2_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r1_skinned_mesh_layer_4),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -12, -32, 49, 0, 0, -75),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r1_mesh_layer_4),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mips_leg_r2_skinned_mesh_layer_4),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 51, 0, 0, 0, 0, -130),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_leg_r2_mesh_layer_4),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, mips_ankle_r1_skinned_mesh_layer_4),
												GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 0, 0, 0, 0, 155),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_ankle_r1_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -21, 41, 0, 0, 180, 50),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, mips_tail_mesh_layer_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mips_switch_opt1),
			GEO_BRANCH(1, mips_switch_opt2),
			GEO_BRANCH(1, mips_switch_opt3),
			GEO_BRANCH(1, mips_switch_opt4),
			GEO_BRANCH(1, mips_switch_opt5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
