#ifndef GROUP15_H
#define GROUP15_H

#include "types.h"

// boo_castle
extern const GeoLayout boo_castle_geo[];
extern const Gfx boo_castle_seg6_dl_06017A10[];
extern const Gfx boo_castle_seg6_dl_06017A78[];
extern const Gfx boo_castle_seg6_dl_06017AD0[];
extern const Gfx boo_castle_seg6_dl_06017CE0[];

// lakitu_cameraman
extern const GeoLayout lakitu_geo[];
extern const Gfx lakitu_seg6_dl_06003C80[];
extern const Gfx lakitu_seg6_dl_06003DB0[];
extern const Gfx lakitu_seg6_dl_06003E30[];
extern const Gfx lakitu_seg6_dl_06004410[];
extern const Gfx lakitu_seg6_dl_06004680[];
extern const Gfx lakitu_seg6_dl_060047E8[];
extern const Gfx lakitu_seg6_dl_060049E0[];
extern const Gfx lakitu_seg6_dl_06004BA8[];
extern const Gfx lakitu_seg6_dl_06004BE8[];
extern const Gfx lakitu_seg6_dl_06004C30[];
extern const Gfx lakitu_seg6_dl_06004C60[];
extern const Gfx lakitu_seg6_dl_06004C88[];
extern const Gfx lakitu_seg6_dl_060051D0[];
extern const Gfx lakitu_seg6_dl_06005218[];
extern const Gfx lakitu_seg6_dl_06005360[];
extern const Gfx lakitu_seg6_dl_06005598[];
extern const Gfx lakitu_seg6_dl_060055E8[];
extern const Gfx lakitu_seg6_dl_06005610[];
extern const struct Animation *const lakitu_seg6_anims_060058F8[];

// mips
extern const GeoLayout mips_switch_opt1[];
extern const GeoLayout mips_switch_opt2[];
extern const GeoLayout mips_switch_opt3[];
extern const GeoLayout mips_switch_opt4[];
extern const GeoLayout mips_switch_opt5[];
extern const GeoLayout mips_geo[];
extern Lights1 mips_mips_yellow_lights;
extern Lights1 mips_mips_orange_lights;
extern Lights1 mips_mips_pink_lights;
extern Lights1 mips_mips_green_lights;
extern Lights1 mips_mips_white_lights;
extern Lights1 mips_mips_cyan_lights;
extern u8 mips_mips_yellow_rgba16[];
extern u8 mips_mips_orange_rgba16[];
extern u8 mips_mips_pink_rgba16[];
extern u8 mips_mips_green_rgba16[];
extern u8 mips_mips_white_rgba16[];
extern u8 mips_mips_blue_rgba16[];
extern Vtx mips_skl_root_mesh_layer_4_vtx_0[17];
extern Gfx mips_skl_root_mesh_layer_4_tri_0[];
extern Vtx mips_arm_l1_skinned_mesh_layer_4_vtx_0[4];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_arm_l1_mesh_layer_4_vtx_0[3];
extern Gfx mips_arm_l1_mesh_layer_4_tri_0[];
extern Vtx mips_arm_l1_mesh_layer_4_vtx_1[11];
extern Gfx mips_arm_l1_mesh_layer_4_tri_1[];
extern Vtx mips_arm_r1_skinned_mesh_layer_4_vtx_0[4];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_arm_r1_mesh_layer_4_vtx_0[3];
extern Gfx mips_arm_r1_mesh_layer_4_tri_0[];
extern Vtx mips_arm_r1_mesh_layer_4_vtx_1[11];
extern Gfx mips_arm_r1_mesh_layer_4_tri_1[];
extern Vtx mips_head1_mesh_layer_4_vtx_0[83];
extern Gfx mips_head1_mesh_layer_4_tri_0[];
extern Vtx mips_ear_l1_mesh_layer_4_vtx_0[8];
extern Gfx mips_ear_l1_mesh_layer_4_tri_0[];
extern Vtx mips_ear_l2_skinned_mesh_layer_4_vtx_0[7];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_ear_l2_mesh_layer_4_vtx_0[8];
extern Gfx mips_ear_l2_mesh_layer_4_tri_0[];
extern Vtx mips_ear_l2_mesh_layer_4_vtx_1[5];
extern Gfx mips_ear_l2_mesh_layer_4_tri_1[];
extern Vtx mips_ear_r1_mesh_layer_4_vtx_0[8];
extern Gfx mips_ear_r1_mesh_layer_4_tri_0[];
extern Vtx mips_ear_r2_skinned_mesh_layer_4_vtx_0[7];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_ear_r2_mesh_layer_4_vtx_0[8];
extern Gfx mips_ear_r2_mesh_layer_4_tri_0[];
extern Vtx mips_ear_r2_mesh_layer_4_vtx_1[5];
extern Gfx mips_ear_r2_mesh_layer_4_tri_1[];
extern Vtx mips_leg_l1_skinned_mesh_layer_4_vtx_0[11];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_leg_l1_mesh_layer_4_vtx_0[8];
extern Gfx mips_leg_l1_mesh_layer_4_tri_0[];
extern Vtx mips_leg_l1_mesh_layer_4_vtx_1[3];
extern Gfx mips_leg_l1_mesh_layer_4_tri_1[];
extern Vtx mips_leg_l2_skinned_mesh_layer_4_vtx_0[8];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_leg_l2_mesh_layer_4_vtx_0[7];
extern Gfx mips_leg_l2_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_l1_skinned_mesh_layer_4_vtx_0[5];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_l1_mesh_layer_4_vtx_0[4];
extern Gfx mips_ankle_l1_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_l2_skinned_mesh_layer_4_vtx_0[8];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_l2_mesh_layer_4_vtx_0[7];
extern Gfx mips_ankle_l2_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_l2_mesh_layer_4_vtx_1[3];
extern Gfx mips_ankle_l2_mesh_layer_4_tri_1[];
extern Vtx mips_leg_r1_skinned_mesh_layer_4_vtx_0[9];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_leg_r1_mesh_layer_4_vtx_0[6];
extern Gfx mips_leg_r1_mesh_layer_4_tri_0[];
extern Vtx mips_leg_r1_mesh_layer_4_vtx_1[3];
extern Gfx mips_leg_r1_mesh_layer_4_tri_1[];
extern Vtx mips_leg_r2_skinned_mesh_layer_4_vtx_0[7];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_leg_r2_mesh_layer_4_vtx_0[7];
extern Gfx mips_leg_r2_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_r1_skinned_mesh_layer_4_vtx_0[5];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_r1_mesh_layer_4_vtx_0[4];
extern Gfx mips_ankle_r1_mesh_layer_4_tri_0[];
extern Vtx mips_ankle_r1_mesh_layer_4_vtx_1[15];
extern Gfx mips_ankle_r1_mesh_layer_4_tri_1[];
extern Vtx mips_tail_mesh_layer_4_vtx_0[4];
extern Gfx mips_tail_mesh_layer_4_tri_0[];
extern Gfx mat_mips_mips_yellow[];
extern Gfx mat_revert_mips_mips_yellow[];
extern Gfx mat_mips_mips_orange[];
extern Gfx mat_revert_mips_mips_orange[];
extern Gfx mat_mips_mips_pink[];
extern Gfx mat_revert_mips_mips_pink[];
extern Gfx mat_mips_mips_green[];
extern Gfx mat_revert_mips_mips_green[];
extern Gfx mat_mips_mips_white[];
extern Gfx mat_revert_mips_mips_white[];
extern Gfx mat_mips_mips_cyan[];
extern Gfx mat_revert_mips_mips_cyan[];
extern Gfx mips_skl_root_mesh_layer_4[];
extern Gfx mips_skl_root_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_skl_root_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_skl_root_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_skl_root_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_skl_root_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_arm_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_arm_l1_mesh_layer_4[];
extern Gfx mips_arm_l1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_arm_l1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_arm_l1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_arm_l1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_arm_l1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_arm_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_arm_r1_mesh_layer_4[];
extern Gfx mips_arm_r1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_arm_r1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_arm_r1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_arm_r1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_arm_r1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_head1_mesh_layer_4[];
extern Gfx mips_head1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_head1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_head1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_head1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_head1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_l1_mesh_layer_4[];
extern Gfx mips_ear_l1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_l1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_l1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_l1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_l1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_l2_mesh_layer_4[];
extern Gfx mips_ear_l2_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_l2_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_l2_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_l2_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_l2_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_r1_mesh_layer_4[];
extern Gfx mips_ear_r1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_r1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_r1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_r1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_r1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_r2_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ear_r2_mesh_layer_4[];
extern Gfx mips_ear_r2_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ear_r2_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ear_r2_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ear_r2_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ear_r2_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_l1_mesh_layer_4[];
extern Gfx mips_leg_l1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_l1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_l1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_l1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_l1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_l2_mesh_layer_4[];
extern Gfx mips_leg_l2_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_l2_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_l2_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_l2_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_l2_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_l1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_l1_mesh_layer_4[];
extern Gfx mips_ankle_l1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_l1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_l1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_l1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_l1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_l2_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_l2_mesh_layer_4[];
extern Gfx mips_ankle_l2_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_l2_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_l2_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_l2_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_l2_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_r1_mesh_layer_4[];
extern Gfx mips_leg_r1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_r1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_r1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_r1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_r1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_r2_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_leg_r2_mesh_layer_4[];
extern Gfx mips_leg_r2_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_leg_r2_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_leg_r2_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_leg_r2_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_leg_r2_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_r1_skinned_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_ankle_r1_mesh_layer_4[];
extern Gfx mips_ankle_r1_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_ankle_r1_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_ankle_r1_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_ankle_r1_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_ankle_r1_mesh_layer_4_mat_override_mips_cyan_4[];
extern Gfx mips_tail_mesh_layer_4[];
extern Gfx mips_tail_mesh_layer_4_mat_override_mips_orange_0[];
extern Gfx mips_tail_mesh_layer_4_mat_override_mips_pink_1[];
extern Gfx mips_tail_mesh_layer_4_mat_override_mips_green_2[];
extern Gfx mips_tail_mesh_layer_4_mat_override_mips_white_3[];
extern Gfx mips_tail_mesh_layer_4_mat_override_mips_cyan_4[];
extern const struct Animation *const mips_animations[];

// toad
extern const GeoLayout toad_geo_000114[];
extern const GeoLayout toad_geo_00027C[];
extern const GeoLayout toad_geo[];
extern const Gfx toad_seg6_dl_06007300[];
extern const Gfx toad_seg6_dl_06007498[];
extern const Gfx toad_seg6_dl_060076C0[];
extern const Gfx toad_seg6_dl_06007710[];
extern const Gfx toad_seg6_us_dl_06007788[];
extern const Gfx toad_seg6_dl_06007960[];
extern const Gfx toad_seg6_dl_06007A48[];
extern const Gfx toad_seg6_us_dl_06007B00[];
extern const Gfx toad_seg6_dl_06007D10[];
extern const Gfx toad_seg6_dl_06007EB0[];
extern const Gfx toad_seg6_dl_060080C0[];
extern const Gfx toad_seg6_dl_060081F8[];
extern const Gfx toad_seg6_dl_060083E8[];
extern const Gfx toad_seg6_dl_06008520[];
extern const Gfx toad_seg6_us_dl_06008608[];
extern const Gfx toad_seg6_dl_06008748[];
extern const Gfx toad_seg6_dl_06008890[];
extern const Gfx toad_seg6_dl_06008A90[];
extern const Gfx toad_seg6_dl_06008BD8[];
extern const struct Animation *const toad_animations[];

#include "toad/geo_header.h"

#include "toad/anim_header.h"

#endif
