const GeoLayout piranha_plant_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 155, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 44, 0, piranha_plant_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 44, 0, piranha_plant_hand_r_4),
					GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_neck1_4),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, piranha_plant_neck1_2_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_neck2_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 306, 0, piranha_plant_neck2_2_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_neck3_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 219, 0, piranha_plant_neck_03_mesh_layer_4),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_upper_mouth_4),
								GEO_ANIMATED_PART(LAYER_ALPHA, 0, 263, 0, piranha_plant_upper_mouth_2_4),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_lower_mouth_4),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, piranha_plant_lower_mouth_2_4),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
