#ifndef YOSHI_SOUNDS_H
#define YOSHI_SOUNDS_H

// Yoshi SFX

// A random number 0-2 is added to the sound ID before playing, producing Yah/Wah/Hoo
#define SOUND_YOSHI_YAH                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_WAH                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 1, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HOO                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 2, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_MUH                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 3, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_YAHOO                       SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 4, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_UH                          SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 5, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HRMM                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 6, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_WAH2                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 7, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_WHOA                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 8, 0xC0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_EEUH                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 9, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_ATTACKED                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 10, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_OOOF                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 11, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_OOOF2                       SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 11, 0xD0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HERE_WE_GO                  SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 12, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_YAWNING                     SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 13, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_SNORING1                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 14, 0x00, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_SNORING2                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 15, 0x00, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_WAAAOOOW                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 16, 0xC0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HAHA                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 17, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HAHA_2                      SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 17, 0xF0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_UH2                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 19, 0xD0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_UH2_2                       SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 19, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_ON_FIRE                     SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 20, 0xA0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_DYING                       SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 21, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_PANTING_COLD                SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 22, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

// A random number 0-2 is added to the sound ID before playing
#define SOUND_YOSHI_PANTING                     SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x18, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

#define SOUND_YOSHI_COUGHING1                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x1B, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_COUGHING2                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x1C, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_COUGHING3                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x1D, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_LICK                        SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x1E, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_PUNCH_HOO                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x1F, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_MAMA_MIA                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x20, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_OKEY_DOKEY                  SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x21, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_NO_VOLUME_LOSS | SOUND_CONSTANT_FREQUENCY | SOUND_DISCRETE)
#define SOUND_YOSHI_GROUND_POUND_WAH            SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x22, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_DROWNING                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x23, 0xF0, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_PUNCH_WAH                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x24, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

// A random number 0-4 is added to the sound ID before playing, producing one of
// Yahoo! (60% chance), Waha! (20%), or Yippee! (20%).
#define SOUND_YOSHI_YAHOO_WAHA_YIPPEE           SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x2B, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

#define SOUND_YOSHI_DOH                         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x30, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_GAME_OVER                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x31, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_HELLO                       SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x32, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_PRESS_START_TO_PLAY         SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x33, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_NO_ECHO | SOUND_DISCRETE)
#define SOUND_YOSHI_TWIRL_BOUNCE                SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x34, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_SNORING3                    SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x35, 0x00, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_SO_LONGA_BOWSER             SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x36, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)
#define SOUND_YOSHI_IMA_TIRED                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x37, 0x80, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

#define SOUND_YOSHI_LETS_A_GO                   SOUND_ARG_LOAD(SOUND_BANK_YOSHI_VOICE, 0x38, 0xFF, SOUND_NO_PRIORITY_LOSS | SOUND_DISCRETE)

#endif // YOSHI_SOUNDS_H